### ISSUE TITLE
Could someone help me with a "simple" example?

### ISSUE THREAD

**Issue by dantedantas** [AlexaCRM/dynamics-webapi-toolkit#77] opened 2022-04-07 12:45 UTC
Hello,

please, maybe do you have a simple example on how to connect, collect records (eg.: incidents) and list it (FetchXML)?
It will be very userful to me and will save me a lot of time.

PS.: I want to try to migrate my APP from the php-crm-toolkit to the dynamics-webapi-toolkit.

I am trying to follow the Tutorial, but no luck.
![image](https://user-images.githubusercontent.com/10854571/162212587-9f41759f-b8ef-4654-be69-ab5173fbbd70.png)

Error:
Fatal error: Uncaught Error: Class 'AlexaCRM\WebAPI\ClientFactory' not found in C:\Tools\xampp\htdocs\WebApi2\index2.php:5 Stack trace: #0 {main} thrown in C:\Tools\xampp\htdocs\WebApi2\index2.php on line 5

Thank you for your support.
Best regards,

Dante

**Comment by georged** [comment] 2022-04-07 23:57
@dantedantas have you run composer?

```
$ composer require alexacrm/dynamics-webapi-toolkit:dev-master
```

**Comment by dantedantas** [comment] 2022-04-08 05:05
Yes, I did.
I will try again.

Em sex, 8 de abr de 2022 01:57, George Doubinski ***@***.***>
escreveu:

**Comment by dantedantas** [comment] 2022-04-08 08:27
I did one time more.
![image](https://user-images.githubusercontent.com/10854571/162390261-51527902-f23d-4ac8-a67f-e89bf55bd0a8.png)

And... it works... I have no idea why. I just ran one time more the compose. As you see, there was no update.
But good. Now it "works" better.

I am getting the error bellow.

```
**Fatal error**: Uncaught AlexaCRM\WebAPI\ToolkitException: 
**Metadata request returned a 403 code in** C:\Tools\xampp\htdocs\WebApi2\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\Client.php:351 Stack trace: 

 #0 C:\Tools\xampp\htdocs\WebApi2\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\Client.php(271): AlexaCRM\WebAPI\Client->retrieveViaFetchXML(Object(AlexaCRM\Xrm\Query\FetchExpression)) 

#1 C:\Tools\xampp\htdocs\WebApi2\index.php(24): AlexaCRM\WebAPI\Client->RetrieveMultiple(Object(AlexaCRM\Xrm\Query\FetchExpression)) 

#2 {main} thrown in C:\Tools\xampp\htdocs\WebApi2\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\Client.php on line 351
```
![image](https://user-images.githubusercontent.com/10854571/162396133-55ce1ad8-f3ee-4ad6-bc1e-a1f8ada88bad.png)

Please, could you help me to find out the reason of the issue?

BR,
Dante

**Comment by georged** [comment] 2022-04-08 09:26
That's probably insufficient permissions. If you attach a logger and set level to Debug then you'll be able to track the issue better. Check the roles assigned to the app user.

**Comment by dantedantas** [comment] 2022-04-12 11:46
Hi @georged, thank you for your reply.

I will be very thankful with your attention and help.
Please, see below the log:

```
[2022-04-12T12:47:12.457991+02:00] WebAPI_2.DEBUG: Initializing Dynamics Web API Toolkit {"settings":{"AlexaCRM\\WebAPI\\OData\\OnlineSettings":{"applicationID":"XXX","applicationSecret":"YYY","certificatePath":"","passphrase":null,"tenantID":null,"apiVersion":"9.0","instanceURI":"https://myorg.crm4.dynamics.com","caBundle":null,"caBundlePath":null,"tlsVerifyPeers":true,"cachePool":[],"logger":[],"callerID":null}},"authentication":"AlexaCRM\\WebAPI\\OData\\OnlineAuthMiddleware","handlers":[]} []
[2022-04-12T12:47:12.700217+02:00] WebAPI_2.DEBUG: Probed https://myorg.crm4.dynamics.com/api/data/v9.0/ for tenant ID {myorg} [] []
[2022-04-12T12:47:12.906791+02:00] WebAPI_2.DEBUG: Retrieved a new access token via https://login.microsoftonline.com/myorg/oauth2/token [] []
[2022-04-12T12:47:13.095735+02:00] WebAPI_2.ERROR: Failed to retrieve OData metadata from https://myorg.crm4.dynamics.com/api/data/v9.0/$metadata {"responseCode":403} []
```
![image](https://user-images.githubusercontent.com/10854571/162944424-9fb32f5b-99a4-4b0b-9793-257fff5e31bd.png)

About the setting of the Application. I asked the Azure Administrator to follow the link below:
https://docs.microsoft.com/en-us/power-apps/developer/data-platform/walkthrough-register-app-azure-active-directory
 
![1](https://user-images.githubusercontent.com/10854571/162951140-1d34b564-d4b7-4454-befe-b373b5d2159b.png)

![2](https://user-images.githubusercontent.com/10854571/162951162-d5d00d81-c5b1-4582-9d51-c01940cf256a.png)

![3](https://user-images.githubusercontent.com/10854571/162951172-a46de833-752d-447d-b273-3cb1212e878a.png)

![4](https://user-images.githubusercontent.com/10854571/162951191-bad02880-fb72-4a37-9609-484c6bfaabe4.png)

![5](https://user-images.githubusercontent.com/10854571/162951263-30adaaa3-6033-4f0d-900b-c6b21904a6f9.png)

Maybe do I missing something?

My code:
![image](https://user-images.githubusercontent.com/10854571/162953049-4fd92991-f25d-45a3-959f-a7d7d2d7763a.png)

Thank you very much.

BR,
Dante

**Comment by dantedantas** [comment] 2022-04-12 13:41
Where could I find this information? Please, could you share with me a screenshot where could I find this info?

**Comment by georged** [comment] 2022-04-12 20:09
@dantedantas Dataverse documentation has all you need: https://docs.microsoft.com/power-platform/admin/database-security#assign-security-roles-to-users-in-an-environment-that-has-a-dataverse-database

**Comment by dantedantas** [comment] 2022-04-13 10:12
Hi @georged , thank you for your feedback.

**I am using HTTP and not HTTPS. Could be it an issue?** (Hope not)

Thank you for the link, but, maybe, do you have a list with the permissions that I would need?

We created 2 APPs with the same config. Tha App that uses C# works fine, my (with PHP), still doesnt work.

I've got user_impersonation granted, but I don't think that I need this for the incident viewer (my tools), but I don't have any read permissions granted. I'm not sure if these need to API permissions or not.

Maybe, could you help me to establish exactly what permissions I need to request?

Thank you ver much.

**Comment by georged** [comment] 2022-04-13 10:41
@dantedantas user_impersonation is API permission, this is not the place to look.
You need to assign roles to the app user in *Dataverse*. Try something like System Administrator role just to see if it works. If it does then you can figure out reduced set of permissions. If it does not work the problem is elsewhere.

**Comment by dantedantas** [comment] 2022-04-13 11:22
@georged Just to be sure. I am using HTTP and not HTTPS. Could be it an issue?

**Comment by georged** [comment] 2022-04-13 11:30
On your site you should be able to use http but you must use https to connect to Dataverse

**Comment by dantedantas** [comment] 2022-06-15 11:02
Dear Georg, I am sorry for my later reply. I moved to a new flat and it was a lot of work, and I was about 1 month in Vacation.
Thank you very much for your help and attention.

Back to the topic...
I am using XAMPP as an internal Web-Server. 
![image](https://user-images.githubusercontent.com/10854571/173810212-a618b2c0-2ad7-4520-adeb-8619ef5da57a.png)

![image](https://user-images.githubusercontent.com/10854571/173780108-a987e4e4-53c2-4f2e-ad6b-34b4f7a01a06.png)

![image](https://user-images.githubusercontent.com/10854571/173811099-77f4dc42-ff7b-4a1d-a8e4-dba4c08072a3.png)

I tried to follow up some tutorials to install the SSL but without luck so far.

[https://stackoverflow.com/questions/64800565/how-to-create-valid-ssl-in-localhost-for-xampp](https://stackoverflow.com/questions/64800565/how-to-create-valid-ssl-in-localhost-for-xampp)

Maybe do you have some idea?
Thank you.

**Comment by dantedantas** [comment] 2022-06-22 14:54
Dear Georg, sorry if I brother you.
Please, could you give me a little bit more help?

![image](https://user-images.githubusercontent.com/10854571/175059060-05de2604-adac-4ddf-9276-6460663a448a.png)

I have inplemented the SSL Cert by following the link (StackOverflow) above, but I am still getting the same issue.

`Fatal error: Uncaught AlexaCRM\WebAPI\ToolkitException: Metadata request returned a 403 code in C:\Tools\xampp\htdocs\WebApi2\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\Client.php:357 Stack trace: #0 C:\Tools\xampp\htdocs\WebApi2\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\Client.php(272): AlexaCRM\WebAPI\Client->retrieveViaFetchXML(Object(AlexaCRM\Xrm\Query\FetchExpression)) #1 C:\Tools\xampp\htdocs\WebApi2\index.php(53): AlexaCRM\WebAPI\Client->RetrieveMultiple(Object(AlexaCRM\Xrm\Query\FetchExpression)) #2 {main} thrown in C:\Tools\xampp\htdocs\WebApi2\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\Client.php on line 357`

Do I miss something?

My code: [https://github.com/AlexaCRM/dynamics-webapi-toolkit/discussions/69](https://github.com/AlexaCRM/dynamics-webapi-toolkit/discussions/69) #69 

Thank you very much.
BR,
Dante

**Comment by georged** [comment] 2022-06-23 10:59
@dantedantas you're getting 403 which means you're not authenticated properly try executing something simple that does not require metadata like WhoAmI: $foo = $client->executeAction('WhoAmI');

**Comment by dantedantas** [comment] 2022-06-28 14:51
Dear Georg. Thank you for youy feedback.

If I sent: $settings->tlsVerifyPeers = false;
Then, I am getting the error:
```
**Fatal error:** Uncaught AlexaCRM\WebAPI\OData\ODataException: 
Client error: `POST https://xxxx.crm4.dynamics.com/api/data/v9.0/WhoAmI` resulted in a `403 Forbidden` response with the following message: `The user is not a member of the organization.` 
in C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\OData\Client.php:245 Stack trace: 
#0 C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\OData\Client.php(615): AlexaCRM\WebAPI\OData\Client->doRequest('POST', 'https://xxx...', NULL) 
#1 C:\Tools\xampp\htdocs\incidentreport\index.php(57): AlexaCRM\WebAPI\OData\Client->executeAction('WhoAmI') 
#2 {main} thrown in C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\OData\Client.php on line 245
```

If I set: $settings->caBundlePath = 'server.crt'; //My local certificate.
Then, I am getting the error:
```
Fatal error: Uncaught AlexaCRM\WebAPI\OData\TransportException: cURL error 77: error setting certificate verify locations: CAfile: server.crt CApath: none (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://xxxx.crm4.dynamics.com/api/data/v9.0/ in C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\OData\Client.php:220 Stack trace: 
#0 C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\OData\Client.php(615): AlexaCRM\WebAPI\OData\Client->doRequest('POST', 'https://xxx...', NULL) 
#1 C:\Tools\xampp\htdocs\incidentreport\index.php(57): AlexaCRM\WebAPI\OData\Client->executeAction('WhoAmI') 
#2 {main} thrown in C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\dynamics-webapi-toolkit\src\WebAPI\OData\Client.php on line 220
```

Some idea that could help me from this blinding? :)

Thank you very much.
BR,
Dante

**Closed** 2022-10-18 10:03 UTC
